services:
  pymoveit2:
    container_name: pymoveit2-sim
    image: ros-humble-desktop
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=:0.0
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./examples:/root/pymoveit2/examples"
      - "./pymoveit2:/root/pymoveit2/pymoveit2"
      - "./shell:/root/pymoveit2/shell"
    tty: true

